// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cognito_identity_pool_id': 'us-east-1:da8c40ac-2ca8-401c-8319-e1da2550e841',
    'aws_cognito_region': 'us-east-1',
    'aws_mobile_analytics_app_id': 'd2aa15559f2e4c77bccf3f5581201c16',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': 'bb8c2bb7-4c34-43ff-9de6-473408eb7f94',
    'aws_project_name': 'home-plan-it',
    'aws_project_region': 'us-east-1',
    'aws_resource_name_prefix': 'homeplanit-mobilehub-1303988138',
    'aws_sign_in_enabled': 'enable',
    'aws_user_pools': 'enable',
    'aws_user_pools_id': 'us-east-1_EB7I2RkH8',
    'aws_user_pools_web_client_id': '2ir6mhgjhms699aqetp00rtks6',
}

export default awsmobile;
