// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
var aws_app_analytics = 'enable';
var aws_cognito_identity_pool_id = 'us-east-1:da8c40ac-2ca8-401c-8319-e1da2550e841';
var aws_cognito_region = 'us-east-1';
var aws_mobile_analytics_app_id = 'd2aa15559f2e4c77bccf3f5581201c16';
var aws_mobile_analytics_app_region = 'us-east-1';
var aws_project_id = 'bb8c2bb7-4c34-43ff-9de6-473408eb7f94';
var aws_project_name = 'home-plan-it';
var aws_project_region = 'us-east-1';
var aws_resource_name_prefix = 'homeplanit-mobilehub-1303988138';
var aws_sign_in_enabled = 'enable';
var aws_user_pools = 'enable';
var aws_user_pools_id = 'us-east-1_EB7I2RkH8';
var aws_user_pools_web_client_id = '2ir6mhgjhms699aqetp00rtks6';

AWS.config.region = aws_project_region;
AWS.config.credentials = new AWS.CognitoIdentityCredentials({
    IdentityPoolId: aws_cognito_identity_pool_id
  }, {
    region: aws_cognito_region
  });
AWS.config.update({customUserAgent: 'MobileHub v0.1'});
