// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cloud_logic': 'enable',
    'aws_cloud_logic_custom': [{"id":"gdn4b5smfa","name":"homeplanit","description":"API for Homeplanit apps","endpoint":"https://gdn4b5smfa.execute-api.us-east-1.amazonaws.com/staging","region":"us-east-1","paths":["/users/data/{id}"]}],
    'aws_cognito_identity_pool_id': 'us-east-1:73be8ae7-3808-497a-b285-a578087e82a2',
    'aws_cognito_region': 'us-east-1',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'homeplanitstaging-hosting-mobilehub-402297778',
    'aws_content_delivery_bucket_region': 'us-east-1',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'drzkt014tfff9.cloudfront.net',
    'aws_dynamodb': 'enable',
    'aws_dynamodb_all_tables_region': 'us-east-1',
    'aws_dynamodb_table_schemas': [{"tableName":"homeplanitstaging-mobilehub-402297778-Users","attributes":[{"name":"userId","type":"S"},{"name":"tasks","type":"L"}],"indexes":[],"region":"us-east-1","hashKey":"userId"}],
    'aws_mandatory_sign_in': 'enable',
    'aws_mobile_analytics_app_id': 'a1f17c3d76b243888f1ad415887857e3',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': 'fb21746f-719c-4a3c-aeac-4c75c9c75551',
    'aws_project_name': 'home-plan-it staging',
    'aws_project_region': 'us-east-1',
    'aws_resource_name_prefix': 'homeplanitstaging-mobilehub-402297778',
    'aws_sign_in_enabled': 'enable',
    'aws_user_pools': 'enable',
    'aws_user_pools_id': 'us-east-1_wC6dKzC07',
    'aws_user_pools_mfa_type': 'OFF',
    'aws_user_pools_web_client_id': '634od51h5n8t7rbnenft7pmu86',
}

export default awsmobile;
